data:
  block_size: 512
  cnhubertsoft_gate: 10
  duration: 2
  encoder: contentvec768l12
  encoder_ckpt: pretrain/contentvec/checkpoint_best_legacy_500.pt
  encoder_hop_size: 320
  encoder_out_channels: 768
  encoder_sample_rate: 16000
  extensions:
    - wav
  f0_extractor: rmvpe
  f0_max: 800
  f0_min: 65
  sampling_rate: 44100
  train_path: data/train
  valid_path: data/val
device: cuda
env:
  expdir: exp/workdir
  gpu_id: 0
infer:
  infer_step: 20
  method: euler
model:
  n_chans: 1024
  n_layers: 12
  n_spk: 209
  t_start: 0.7
  type: RectifiedFlow
  use_pitch_aug: true
  win_length: 2048
model_type_index: 0
spks:
  - "ACESinger_10KuroBousuku-CN"
  - "ACESinger_11Barber-CN"
  - "ACESinger_12ChuMing-CN"
  - "ACESinger_13ChangGe-CN"
  - "ACESinger_14QueHe-CN"
  - "ACESinger_15QiXuan-CN"
  - "ACESinger_16NamineRitsu-CN"
  - "ACESinger_17LiYuan-CN"
  - "ACESinger_18WenLi-CN"
  - "ACESinger_19RanHuhu-CN"
  - "ACESinger_1Crimson-CN"
  - "ACESinger_20HuoLian-CN"
  - "ACESinger_21XiaoYe-CN"
  - "ACESinger_22QiLi-CN"
  - "ACESinger_23QiFu-CN"
  - "ACESinger_24XiaoMo-CN"
  - "ACESinger_25YunHao-CN"
  - "ACESinger_26ChuCi-CN"
  - "ACESinger_27Tarara-CN"
  - "ACESinger_28LuanMing-CN"
  - "ACESinger_29HiragiYuki-CN"
  - "ACESinger_2Orange-CN"
  - "ACESinger_30TuYuan-CN"
  - "ACESinger_3Tangerine-CN"
  - "ACESinger_4Growl-CN"
  - "ACESinger_5Steel-CN"
  - "ACESinger_6Ghost-CN"
  - "ACESinger_7David-CN"
  - "ACESinger_8Lien-CN"
  - "ACESinger_9Bianca-CN"
  - "female_1_七线阁"
  - "female_2_七线阁"
  - "female_CHENXIAOMAN_48k_32bit"
  - "female_Itako"
  - "female_Kiritan"
  - "female_QQ2320796469_wav"
  - "m4Alto"
  - "m4Bass"
  - "m4Soprano"
  - "m4Tenor"
  - "male_1_七线阁"
  - "male_2_七线阁"
  - "male_QQ1477746596_48k_32bit"
  - "male_QQ1599180997_44.1k_16bit_noclean"
  - "male_QQ2222225007_48k"
  - "male_QQ247073005"
  - "male_QQ450676787"
  - "male_QQ46618796_44.1k"
  - "male_QQ467931176"
  - "昙花galgame_ml"
  - "os_opencpop"
  - "Sunshine_Ting干声2"
  - "Sunshine_wik干声"
  - "Sunshine_七-干声"
  - "Sunshine_何文熙-干声"
  - "Sunshine_冷柚-干声"
  - "Sunshine_哆-干声"
  - "Sunshine_啊静-干声"
  - "Sunshine_小景-干声"
  - "Sunshine_执-干声"
  - "Sunshine_拘梦-干声"
  - "Sunshine_旺旺-干声"
  - "Sunshine_沈郁-干声"
  - "Sunshine_海湾干声"
  - "Sunshine_潮品干声1"
  - "Sunshine_瑶一瑶第一次干声"
  - "Sunshine_艾瑞干声"
  - "Sunshine_金满满-干声"
  - "Sunshine_黎-干声"
  - "vctk_p225"
  - "vctk_p226"
  - "vctk_p227"
  - "vctk_p228"
  - "vctk_p229"
  - "vctk_p230"
  - "vctk_p231"
  - "vctk_p232"
  - "vctk_p233"
  - "vctk_p234"
  - "vctk_p236"
  - "vctk_p237"
  - "vctk_p238"
  - "vctk_p239"
  - "vctk_p240"
  - "vctk_p241"
  - "vctk_p243"
  - "vctk_p244"
  - "vctk_p245"
  - "vctk_p246"
  - "vctk_p247"
  - "vctk_p248"
  - "vctk_p249"
  - "vctk_p250"
  - "vctk_p251"
  - "vctk_p252"
  - "vctk_p253"
  - "vctk_p254"
  - "vctk_p255"
  - "vctk_p256"
  - "vctk_p257"
  - "vctk_p258"
  - "vctk_p259"
  - "vctk_p260"
  - "vctk_p261"
  - "vctk_p262"
  - "vctk_p263"
  - "vctk_p264"
  - "vctk_p265"
  - "vctk_p266"
  - "vctk_p267"
  - "vctk_p268"
  - "vctk_p269"
  - "vctk_p270"
  - "vctk_p271"
  - "vctk_p272"
  - "vctk_p273"
  - "vctk_p274"
  - "vctk_p275"
  - "vctk_p276"
  - "vctk_p277"
  - "vctk_p278"
  - "vctk_p279"
  - "vctk_p280"
  - "vctk_p281"
  - "vctk_p282"
  - "vctk_p283"
  - "vctk_p284"
  - "vctk_p285"
  - "vctk_p286"
  - "vctk_p287"
  - "vctk_p288"
  - "vctk_p292"
  - "vctk_p293"
  - "vctk_p294"
  - "vctk_p295"
  - "vctk_p297"
  - "vctk_p298"
  - "vctk_p299"
  - "vctk_p300"
  - "vctk_p301"
  - "vctk_p302"
  - "vctk_p303"
  - "vctk_p304"
  - "vctk_p305"
  - "vctk_p306"
  - "vctk_p307"
  - "vctk_p308"
  - "vctk_p310"
  - "vctk_p311"
  - "vctk_p312"
  - "vctk_p313"
  - "vctk_p314"
  - "vctk_p315"
  - "vctk_p316"
  - "vctk_p317"
  - "vctk_p318"
  - "vctk_p323"
  - "vctk_p326"
  - "vctk_p329"
  - "vctk_p330"
  - "vctk_p333"
  - "vctk_p334"
  - "vctk_p335"
  - "vctk_p336"
  - "vctk_p339"
  - "vctk_p340"
  - "vctk_p341"
  - "vctk_p343"
  - "vctk_p345"
  - "vctk_p347"
  - "vctk_p351"
  - "vctk_p360"
  - "vctk_p361"
  - "vctk_p362"
  - "vctk_p363"
  - "vctk_p364"
  - "vctk_p374"
  - "vctk_p376"
  - "vctk_s5"
  - "少杰_Rap_spk1_txt"
  - "少杰_Talk_spk2_nolab"
  - "少杰_tts_en"
  - "少杰_tts_普通话"
  - "昙花galgame_84"
  - "昙花galgame_hl"
  - "昙花galgame_lb"
  - "昙花galgame_lr"
  - "昙花galgame_ql"
  - "昙花galgame_qy"
  - "昙花galgame_xl"
  - "昙花galgame_xls"
  - "昙花galgame_xy"
  - "昙花galgame_zr"
  - "俊达萌"
  - "QQ3069173622_X"
  - "QQ3069173622_moment"
  - "QQ3069173622_nupin"
  - "QQ3069173622_ring"
  - "QQ3069173622_weixiao"
  - "QQ3069173622_上川"
  - "QQ3069173622_东北"
  - "QQ3069173622_大熊"
  - "QQ3069173622_小胖儿"
  - "QQ3069173622_小黄"
  - "QQ3069173622_懿安"
  - "QQ3069173622_李荣"
  - "QQ3069173622_皓"
  - "QQ3069173622_薄荷"
  - "QQ3069173622_黛"
  - "female_ONIKU_KURUMI"
  - "female_kodoku"
  - "female_?雨星サイファ"

train:
  val_workers: 10
  amp_dtype: fp32
  batch_size: 80
  cache_all_data: false
  cache_device: cpu
  cache_fp16: true
  decay_step: 50000
  epochs: 100000
  gamma: 0.5
  interval_force_save: 10000
  interval_log: 1
  interval_val: 1000
  lambda_ddsp: 1
  lr: 0.0002
  num_workers: 2
  save_opt: false
  weight_decay: 0
vocoder:
  ckpt: pretrain/nsf_hifigan/model
  type: nsf-hifigan
