data:
  block_size: 512
  cnhubertsoft_gate: 10
  duration: 2
  encoder: contentvec768l12
  encoder_ckpt: pretrain/contentvec/checkpoint_best_legacy_500.pt
  encoder_hop_size: 320
  encoder_out_channels: 768
  encoder_sample_rate: 16000
  extensions:
  - wav
  f0_extractor: fcpe
  f0_max: 800
  f0_min: 65
  sampling_rate: 44100
  train_path: data/train
  valid_path: data/val
device: cuda
env:
  expdir: exp/workdir
  gpu_id: 0
infer:
  infer_step: 20
  method: euler
model:
  n_chans: 512
  n_layers: 6
  n_spk: 1
  t_start: 0.7
  type: RectifiedFlow
  use_pitch_aug: true
  win_length: 2048
model_type_index: 0
spks:
- QQ756107584
train:
  amp_dtype: fp32
  batch_size: 60
  cache_all_data: false
  cache_device: cpu
  cache_fp16: true
  decay_step: 50000
  epochs: 100000
  gamma: 0.5
  interval_force_save: 1000
  interval_log: 1
  interval_val: 1000
  lambda_ddsp: 1
  lr: 0.0002
  num_workers: 2
  save_opt: false
  val_workers: 10
  weight_decay: 0
vocoder:
  ckpt: pretrain/nsf_hifigan/model
  type: nsf-hifigan
